# Generated by Django 5.0.4 on 2024-04-09 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(db_index=True, max_length=16, unique=True)),
                ('valid_time', models.CharField(max_length=4)),
                ('card_type', models.CharField(choices=[('humo', 'humo'), ('uzcard', 'uzcard'), ('visa', 'visa')], max_length=20)),
                ('bank_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(choices=[('humo', 'humo'), ('uzcard', 'uzcard'), ('visa', 'visa')], on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
